# Generated by Django 2.1 on 2020-05-04 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20200504_2051'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookinstance',
            name='pdf',
            field=models.FileField(null=True, upload_to='documents/'),
        ),
    ]
